function showResume() {
    var header1 = document.createElement("H1");
    header1.textContent = 'Sujit Saroj';
    document.body.appendChild(header1);
    var horiz_rule1 = document.createElement("hr");
    document.body.appendChild(horiz_rule1);
    var header2 = document.createElement("h3");
    header2.textContent = 'Education';
    document.body.appendChild(header2);
    var horiz_rule2 = document.createElement("hr");
    document.body.appendChild(horiz_rule2);
    var para1 = document.createElement('p');
    para1.textContent = 'B Tech in Information Technology from K. J. Somaiya Institute of Engineering and Information Technology (current)';
    document.body.appendChild(para1);
    var para2 = document.createElement('p');
    para2.textContent = 'HSC from RJ Collage';
    document.body.appendChild(para2);
    var para3 = document.createElement('p');
    para3.textContent = ' Std I - X from Hindi High School';
    document.body.appendChild(para3);
    var horiz_rule3 = document.createElement("hr");
    document.body.appendChild(horiz_rule3);
    var header3 = document.createElement("h3");
    header3.textContent = 'Technical Skills and Interests';
    document.body.appendChild(header3);
    var horiz_rule4 = document.createElement("hr");
    document.body.appendChild(horiz_rule4);
    var para4 = document.createElement('p');
    para4.textContent = 'Web Development using Frameworks such as  React, Angular';
    document.body.appendChild(para4);
    var para5 = document.createElement('p');
    para5.textContent = 'Programming Essentials with Python, Java, C, C++';
    document.body.appendChild(para5);
    var para6 = document.createElement('p');
    para6.textContent = 'Knowledge of Computer Hardware and Components';
    document.body.appendChild(para6);
    var para7 = document.createElement('p');
    para7.textContent = 'Fundamentals of Machine Learning, Internet of Things, etc.';
    document.body.appendChild(para7);
}
